## 0. Review of stationarity tests using *arch*.
* ADF
* KPSS
* PP

In [1]:
import pandas as pd

In [2]:
from moddata import load_data

In [3]:
%matplotlib inline

In [4]:
import matplotlib as pyplot

## 1. Load Data on Polish Banks' Stock Prices

In [5]:
banks = load_data("pl_banking_stocks")

In [9]:
banks.head(3)

ticker         citi                                             bos          \
variable       open     high      low    close       volume    open    high
date
2005-01-03  18.0131  18.3246  17.9535  18.1257  5539.323620  46.810  47.897
2005-01-04  18.1257  18.1257  17.7842  18.0971  3145.922880  46.810  47.897
2005-01-05  17.8975  17.8975  17.6156  17.8975  4523.282897  47.697  47.697

ticker                             ...    pkobp                             \
variable       low   close volume  ...     open     high      low    close
date                               ...
2005-01-03  46.710  47.897  777.0  ...  15.2733  15.6520  15.2198  15.4907
2005-01-04  46.710  47.897  777.0  ...  15.3820  15.4907  15.2198  15.3820
2005-01-05  46.999  46.999  184.0  ...  15.2733  15.3820  14.9438  14.9438

ticker                   santander
variable          volume      open     high      low    close         volume
date
2005-01-03  2.591331e+06   53.9473  54.7852  52.7778  53.3327   25392.744651
2005-01-04  1.816242e+06   53.3327  53.3925  52.7778  53.3327  126064.341850
2005-01-05  2.526285e+06   52.7778  53.1149  52.7183  53.0552  323837.683900

[3 rows x 40 columns]

In [11]:
mbank = banks.loc[:, ("mbank", slice(None))]
mbank.head(3)

ticker       mbank
variable      open    high     low   close   volume
date
2005-01-03  93.002  96.277  93.002  95.055  25608.0
2005-01-04  95.055  96.688  95.055  96.688  25524.0
2005-01-05  94.641  97.099  94.641  95.055  15780.0

## 2. ADF (Augmented Dickey-Fuller) Test

## 3. KPSS (Kwiatkowski-Phillips-Schmidt-Shin) Test

## 4. PP (Phillips-Peron) Test